coordinator=true
node-scheduler.include-coordinator=true
discovery.uri=http://127.0.0.1:8080
http-server.http.port=8080
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/var/lib/ods-trino/tls/server.p12
http-server.https.keystore.key=${ENV:TRINO_TLS_PASSWORD}
http-server.authentication.type=PASSWORD
http-server.authentication.allow-insecure-over-http=false
internal-communication.shared-secret=${ENV:TRINO_INTERNAL_SECRET}
catalog.management=static
query.max-memory=512MB
query.max-memory-per-node=512MB
query.max-total-memory=768MB
query.max-run-time=5m
query.max-execution-time=4m
query.max-length=1000000
query.max-stage-count=30
task.concurrency=2
